application:
  symbols:
    -
      name: EURUSD
      strategyName: StandardStrategy
      parameters:
        timeframe: 1m
    - name: USDJPY
      strategyName: StandardStrategy
      parameters:
        timeframe: 1m