application:
  mode: LIVE
  symbols:
    -
      name: EURUSD
      strategyName: StandardStrategy
      parameters:
        timeframe: 1m
        historicDataSize: 200
    - name: USDJPY
      strategyName: StandardStrategy
      parameters:
        timeframe: 1m
        historicDataSize: 200